apiVersion: v1
kind: ConfigMap
metadata:
  name: my-website-content
  namespace: nginx-demo-configmap
data:
  index.html: |
    <html>
      <body style='font-family: sans-serif; text-align: center; margin-top: 50px;'>
        <h1>Welcome to OpenShift!</h1>
        <p>This HTML file is not inside the container image.</p>
        <p>It is being injected live via a Kubernetes ConfigMap!</p>
      </body>
    </html>
