apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx-demo-configmap
spec:
  selector:
    app: nginx-configmap-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
