apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-gitops
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: docker.io/bitnami/nginx:latest # Your requested image
        ports:
        - containerPort: 8080 # Bitnami Nginx uses 8080 by default
