apiVersion: v1
kind: Pod
metadata:
  name: shared-volume-pod
  labels:
    app: shared-nginx
spec:
  # ---------------------------------------------------
  # Container 1: The NGINX Web Server (The Reader)
  # ---------------------------------------------------
  containers:
  - name: nginx-web
    image: docker.io/bitnami/nginx:latest
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: shared-html-volume
      # Bitnami NGINX serves files from the /app directory by default
      mountPath: /app

  # ---------------------------------------------------
  # Container 2: The Sidecar (The Writer)
  # ---------------------------------------------------
  - name: sidecar-writer
    image: docker.io/busybox:latest
    # This script writes a new index.html file every 5 seconds
    command: 
    - /bin/sh
    - -c
    - |
      while true; do
        echo "<html><body><h2>Time is: $(date)</h2></body></html>" > /shared-data/index.html
        sleep 5
      done
    volumeMounts:
    - name: shared-html-volume
      # The sidecar mounts the SAME volume, but can call the folder whatever it wants
      mountPath: /shared-data

  # ---------------------------------------------------
  # The Pod-Level Volume Definition
  # ---------------------------------------------------
  volumes:
  - name: shared-html-volume
    emptyDir: {}
